### PR TITLE
Docker implementation

### PR DESCRIPTION
**Pull request by kng**

### CODE REVIEW

**Comment by darksidelemm** [comment]
This is a great addition, thanks!

Since i'm a pretty big noob at docker, it would be good to have a setup guide for using this docker image, along the lines of: https://github.com/projecthorus/radiosonde_auto_rx/wiki/Docker

Pre-built images would also be nice to provide, which we are doing for auto_rx and chasemapper already.

**Comment by kng** [comment]
Added README-Docker.md with installation and basic useage

**Comment by kng** [comment]
I am quite unfamiliar with the automatic generation of images, I can give it a try but it is pure fumbling in the dark.

**Comment by kng** [comment]
Yeah, nah, I have no clue. I don't know how to verify that this is working or not.

**Pull request merged**
