### PR TITLE
added payload IDs

### PR DESCRIPTION
**Pull request by zero-one01**

### CODE REVIEW

**Comment by darksidelemm** [comment]
Please adjust these so they continue on from the last available ID (at the moment 635)

**Comment by darksidelemm** [comment]
Also... why so many IDs allocated? What are your plans here? Please don't allocate yourself a bunch of IDs that you're never going to use.

**Comment by darksidelemm** [comment]
Update - now ID 636 is the next available ID

**Comment by zero-one01** [comment]
given that there some higher IDs already assigned at the bottom of the list I assumed that I can choose some available numbers.

currently there are 3-4 radio sondes at my student association for flying high altitude balloons (next launch is planned for the 16.-18.) and I got additional 3 at home for testing.

what would be an appropriate number of IDs ? usually we fly a balloon with 2 sondes in case one gives up during the flight

**Comment by darksidelemm** [comment]
Assign enough IDs that you have enough IDs for the maximum number of balloons you might have in the air simultaneously. 
For testing you don't need to be using a custom assigned ID - that's what the 4FSKTEST-V2 ID is for.

**Comment by zero-one01** [comment]
thanks for clarification. I've fixed the numbers and reduced the IDs to 4

**Pull request merged**
