### PR TITLE
Update payload_id_list.txt

### PR DESCRIPTION
**Pull request by KubaEPJ**

### CODE REVIEW

**Comment by darksidelemm** [comment]
Just to check, are you planing on flying any other trackers along with the 4FSK? The convention now seems to be to use CALLSIGN-4FSK for the 4FSK tracker, and CALLSIGN for RTTY/LORA/whatever.

**Comment by KubaEPJ** [comment]
i think about mode 4FSK 

PLSAT-4FSK

**Comment by darksidelemm** [comment]
If you want to use PLSAT-4FSK, just re-commit with that change and I'm happy to merge.

**Comment by darksidelemm** [comment]
Not sure why you closed this PR? If you just modify the file and commit to your patch-2 branch it can be merged.

**Comment by KubaEPJ** [comment]
Sorry by accident

Kuba

**Review by KubaEPJ — COMMENTED** [review]
PLSAT-4FSK

**Comment by darksidelemm** [comment]
You need to make your changes to the payload ID list, commit then, then push them up to your patch-2 branch (e.g. git push origin patch-2). They should then show up here.

**Comment by KubaEPJ** [comment]
please check

**Comment by darksidelemm** [comment]
It looks like you haven't pushed your changes... If you did that, there will be a new commit showing up on this 'conversation' page.

**Comment by KubaEPJ** [comment]
I've been here for 2 days, please give me some time :-)

**Comment by darksidelemm** [comment]
At this point it might just be faster if you just let me know what callsign you would like - I can quickly allocate an ID for you...

**Pull request closed without merging**
